name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
     - id: foo
       uses: dropecho/.github/.github/workflows/haxe-ci.yml@main
    # uses: dropecho/.github/.github/workflows/haxe-ci.yml@main
    # secrets: inherit
